using System;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Foundry.Schema.Compiler;

var builder = WebApplication.CreateBuilder(args);

// Enable CORS for frontend Vite server
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll", policy =>
    {
        policy.WithOrigins("http://localhost:5173", "http://localhost:5174", "http://127.0.0.1:5173")
              .AllowAnyHeader()
              .AllowAnyMethod();
    });
});

builder.Services.AddHttpClient();

var app = builder.Build();

app.UseCors("AllowAll");

// API endpoint to compile JSON schema to C# POCO classes
app.MapPost("/api/compile", (SchemaModel schema) =>
{
    try
    {
        if (schema == null || string.IsNullOrEmpty(schema.Namespace))
        {
            return Results.BadRequest(new { error = "Invalid schema. Namespace is required." });
        }

        var files = PocoGenerator.Generate(schema);
        return Results.Ok(new { files });
    }
    catch (Exception ex)
    {
        return Results.Problem($"Compilation failed: {ex.Message}");
    }
});

// API proxy to compile prompt using local Ollama model
app.MapPost("/api/ai/prompt", async (AiRequest request, IHttpClientFactory httpClientFactory) =>
{
    try
    {
        if (string.IsNullOrEmpty(request.Prompt))
        {
            return Results.BadRequest(new { error = "Prompt is required." });
        }

        var currentSchemaJson = JsonSerializer.Serialize(request.CurrentSchema ?? new SchemaModel(), new JsonSerializerOptions { WriteIndented = true });

        var systemPrompt = $@"You are an expert software architect and UML designer.
You will update the intermediate JSON Schema matching the specification based on the user's instructions.
The current schema is:
{currentSchemaJson}

The user's instruction is:
""{request.Prompt}""

Return ONLY the complete updated JSON schema. Follow these rules:
1. Ensure the output is valid JSON matching the Schema structure.
2. The JSON must contain key fields: 'Namespace', 'Entities', and 'Enums'.
3. Entities must have 'Name', 'SoftDelete', 'Auditable', 'Properties', and 'Indexes'.
4. Properties must have 'Name', 'Type', 'IsKey', 'IsEnum', and 'Attributes' array.
5. Attributes can include: 'Required', 'Index', 'Unique', 'TextIndex', 'Encrypt', 'Mask', 'MaskEmail'.
6. Enums must have 'Name' and 'Values' string list.
7. Reply with ONLY raw JSON. No markdown ticks, no extra text, just the raw JSON object.";

        var client = httpClientFactory.CreateClient();
        
        var ollamaHost = !string.IsNullOrWhiteSpace(request.OllamaHost)
            ? request.OllamaHost.Trim()
            : Environment.GetEnvironmentVariable("OLLAMA_HOST") ?? "http://edgexpert-c1ad.local:11434";
        var ollamaUrl = $"{ollamaHost}/api/generate";

        var ollamaRequest = new
        {
            model = !string.IsNullOrWhiteSpace(request.OllamaModel)
                ? request.OllamaModel.Trim()
                : "qwen3-coder:30b",
            prompt = systemPrompt,
            stream = false,
            format = "json"
        };

        var response = await client.PostAsJsonAsync(ollamaUrl, ollamaRequest);
        if (!response.IsSuccessStatusCode)
        {
            var errContent = await response.Content.ReadAsStringAsync();
            return Results.Problem($"Ollama request failed: {errContent}");
        }

        var ollamaResponse = await response.Content.ReadFromJsonAsync<OllamaResponse>();
        if (ollamaResponse == null || string.IsNullOrEmpty(ollamaResponse.Response))
        {
            return Results.Problem("Ollama returned an empty response.");
        }

        // Parse the inner JSON response generated by the model
        var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
        var updatedSchema = JsonSerializer.Deserialize<SchemaModel>(ollamaResponse.Response, options);
        
        return Results.Ok(updatedSchema);
    }
    catch (JsonException ex)
    {
        return Results.Problem($"Failed to parse AI-generated schema: {ex.Message}");
    }
    catch (Exception ex)
    {
        return Results.Problem($"AI request failed: {ex.Message}");
    }
});

app.MapGet("/api/ai/models", async (string host, IHttpClientFactory httpClientFactory) =>
{
    try
    {
        if (string.IsNullOrWhiteSpace(host))
        {
            return Results.BadRequest(new { error = "Host is required." });
        }

        var client = httpClientFactory.CreateClient();
        client.Timeout = TimeSpan.FromSeconds(5); // Fast timeout for validation

        var ollamaUrl = $"{host.TrimEnd('/')}/api/tags";
        var response = await client.GetAsync(ollamaUrl);

        if (!response.IsSuccessStatusCode)
        {
            return Results.Problem($"Failed to query Ollama: {response.ReasonPhrase}");
        }

        var tagsResponse = await response.Content.ReadFromJsonAsync<OllamaTagsResponse>();
        if (tagsResponse == null || tagsResponse.Models == null)
        {
            return Results.Ok(new List<string>());
        }

        var modelNames = tagsResponse.Models.Select(m => m.Name).ToList();
        return Results.Ok(modelNames);
    }
    catch (Exception ex)
    {
        return Results.Problem($"Could not connect to Ollama host: {ex.Message}");
    }
});

app.MapPost("/api/save-pocos", (SaveRequest request) =>
{
    try
    {
        if (request == null || string.IsNullOrEmpty(request.OutputPath))
        {
            return Results.BadRequest(new { error = "Invalid request. OutputPath is required." });
        }

        // Validate the output path is within an allowed directory to prevent path traversal
        var resolvedPath = Path.GetFullPath(request.OutputPath);
        var allowedRoot = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "..", ".."));
        if (!resolvedPath.StartsWith(allowedRoot, StringComparison.OrdinalIgnoreCase))
        {
            return Results.BadRequest(new { error = $"Output path must be within the workspace: {allowedRoot}" });
        }

        Directory.CreateDirectory(resolvedPath);

        foreach (var file in request.Files)
        {
            var filePath = Path.Combine(resolvedPath, file.Key);
            File.WriteAllText(filePath, file.Value);
        }

        return Results.Ok(new { message = $"Successfully saved {request.Files.Count} classes to: {resolvedPath}" });
    }
    catch (Exception ex)
    {
        return Results.Problem($"Failed to save files locally: {ex.Message}");
    }
});

app.MapPost("/api/save-manifest", (SaveManifestRequest request) =>
{
    try
    {
        if (request == null || string.IsNullOrEmpty(request.OutputPath))
        {
            return Results.BadRequest(new { error = "Invalid request. OutputPath is required." });
        }

        // Validate the output path is within an allowed directory to prevent path traversal
        var targetPath = Path.GetFullPath(request.OutputPath);
        var allowedRoot = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "..", ".."));
        if (!targetPath.StartsWith(allowedRoot, StringComparison.OrdinalIgnoreCase))
        {
            return Results.BadRequest(new { error = $"Output path must be within the workspace: {allowedRoot}" });
        }

        var directory = Path.GetDirectoryName(targetPath);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        var manifestJson = JsonSerializer.Serialize(request.Manifest, new JsonSerializerOptions { WriteIndented = true });
        File.WriteAllText(targetPath, manifestJson);

        return Results.Ok(new { message = $"Successfully saved api-manifest.json to: {targetPath}" });
    }
    catch (Exception ex)
    {
        return Results.Problem($"Failed to save manifest file locally: {ex.Message}");
    }
});

app.Run();

public record AiRequest
{
    public string Prompt { get; init; } = string.Empty;
    public SchemaModel? CurrentSchema { get; init; }
    public string? OllamaHost { get; init; }
    public string? OllamaModel { get; init; }
}

public record SaveRequest
{
    public Dictionary<string, string> Files { get; init; } = new();
    public string OutputPath { get; init; } = string.Empty;
}

public record SaveManifestRequest
{
    public object Manifest { get; init; } = null!;
    public string OutputPath { get; init; } = string.Empty;
}

public record OllamaResponse
{
    [JsonPropertyName("response")]
    public string Response { get; init; } = string.Empty;
}

public record OllamaTagsResponse
{
    [JsonPropertyName("models")]
    public List<OllamaTagModel>? Models { get; init; }
}

public record OllamaTagModel
{
    [JsonPropertyName("name")]
    public string Name { get; init; } = string.Empty;
}
